version:  '3.2'
services:
# 
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: admin
            MONGO_INITDB_DATABSE: clientDB
        ports:
            - 27017:27017  
        volumes:
            - mongoDB:/data/db
        networks:
            - packform


    postgres:
        image: postgres:11.8
        restart: always
        environment:
            POSTGRES_PASSWORD: "admin"
        ports:
            - 5432:5432  
        volumes:
            - postgresDB:/var/lib/postgresql/data
            
        networks:
            - packform
        

    mongo-express:
        image: mongo-express
        restart: always
        depends_on:
            - mongo
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: admin
        networks:
            - packform

volumes:
    postgresDB:
    mongoDB:

networks:
    packform: